# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fccd32889255c990c824da2621b0544e801f42c6d1fd76f11170aeb1caf16f922a935ffb8d7da66e8b2fc56c26e48a3fab9b2b17cf4c7954b5cbe11e7a92b8c

test:
  secret_key_base: 1c08a86dd2c92bcd39586db71f528f57b11ee34700b0643f34ead44e3d55cf42a3c096ce9a102277af113ccf04097b3e8532b3bf4f316e106d79bc248af818b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
